export const mockData = [
  {
    id: "#1248",
    name: "Sadik Hasan",
    duration: "03 hr",
    start: "07:15 am",
    end: "10:15 am",
    due: "05 hr",
    department: "Design",
    project: "CRM Project",
    notes: "Working on Data Management...",
    status: "none",
  },
  {
    id: "#1249",
    name: "Sadik Hasan",
    duration: "3 hr 30 min",
    start: "08:30 am",
    end: "11:30 am",
    due: "4 hr 30 min",
    department: "Development",
    project: "HRM Project",
    notes: "Working on Data Management...",
    status: "none",
  },
  {
    id: "#1248",
    name: "Sadik Hasan",
    duration: "03 hr",
    start: "07:15 am",
    end: "10:15 am",
    due: "05 hr",
    department: "Product",
    project: "CRM Project",
    notes: "Working on Data Management...",
    status: "approved",
  },
  {
    id: "#1249",
    name: "Hasibul Hasan",
    duration: "3 hr 30 min",
    start: "08:30 am",
    end: "11:30 am",
    due: "4 hr 30 min",
    department: "Sales",
    project: "HRM Project",
    notes: "Working on Data Management...",
    status: "none",
  },
  {
    id: "#1249",
    name: "Hasibul Hasan",
    duration: "3 hr 30 min",
    start: "08:30 am",
    end: "11:30 am",
    due: "4 hr 30 min",
    department: "Product",
    project: "HRM Project",
    notes: "Working on Data Management...",
    status: "none",
  },
  {
    id: "#1248",
    name: "Sadik Hasan",
    duration: "03 hr",
    start: "07:15 am",
    end: "10:15 am",
    due: "05 hr",
    department: "Design",
    project: "CRM Project",
    notes: "Working on Data Management...",
    status: "none",
  },
  {
    id: "#1249",
    name: "Sadik Hasan",
    duration: "3 hr 30 min",
    start: "08:30 am",
    end: "11:30 am",
    due: "4 hr 30 min",
    department: "Development",
    project: "HRM Project",
    notes: "Working on Data Management...",
    status: "rejected",
  },
  {
    id: "#1248",
    name: "Sadik Hasan",
    duration: "03 hr",
    start: "07:15 am",
    end: "10:15 am",
    due: "05 hr",
    department: "Product",
    project: "CRM Project",
    notes: "Working on Data Management...",
    status: "approved",
  },
  {
    id: "#1249",
    name: "Hasibul Hasan",
    duration: "3 hr 30 min",
    start: "08:30 am",
    end: "11:30 am",
    due: "4 hr 30 min",
    department: "Sales",
    project: "HRM Project",
    notes: "Working on Data Management...",
    status: "approved",
  },
  {
    id: "#1249",
    name: "Hasibul Hasan",
    duration: "3 hr 30 min",
    start: "08:30 am",
    end: "11:30 am",
    due: "4 hr 30 min",
    department: "Product",
    project: "HRM Project",
    notes: "Working on Data Management...",
    status: "rejected",
  },
];